# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import datetime
import decimal
import pydantic


class Account(pydantic.BaseModel):
    account_id: int
    user_id: int
    name: str
    balance: decimal.Decimal
    currency_id: int


class Category(pydantic.BaseModel):
    category_id: int
    user_id: int
    name: str
    type: str


class Currency(pydantic.BaseModel):
    currency_id: int
    name: str
    iso_code: str
    symbol: str


class Rate(pydantic.BaseModel):
    rate_id: int
    from_currency: int
    to_currency: int
    rate: decimal.Decimal
    updated_at: datetime.datetime


class Transaction(pydantic.BaseModel):
    transaction_id: int
    account_id: int
    category_id: int
    amount: decimal.Decimal


class UserAccount(pydantic.BaseModel):
    user_id: int
    user_tg_id: int
    balance: decimal.Decimal
    currency_id: int
